### PR TITLE
New Card - Fireball + basic prefab

### PR DESCRIPTION
**Pull request by DrSalazar**
New card - Fireball using type Kunai with a different prefab, damage,
and range.

### CODE REVIEW

**Comment by cookie966507** [comment]
For art sake, are you wanting this to be a simple fireball or did you have something else in mind? I would assume so, but I'd rather not have to make two different art pieces because I assumed too much...

**Comment by JonathanHunter** [comment]
What is the Assets/Terrain/New Terrain.asset you commited?  Also please remove ProjectSettings/ProjectSettings.asset and ProjectSettings/ProjectVersion.txt, they are irrelevant to your commit.  After that I'll should be able to merge it :)

**Comment by DrSalazar** [comment]
Honestly, something simple would be perfectly fine

**Comment by NealKaviratna** [comment]
Did some housekeeping on the pull request, as well as merged in the changes ahead of the commit to ensure everything was squared away. Merged the pull request.

**Pull request merged**
