### PR TITLE
In-Game menu's functional

### PR DESCRIPTION
**Pull request by NealKaviratna**
Base functionality for in game menus completed

### CODE REVIEW

**Comment by JonathanHunter** [comment]
+1

**Comment by cookie966507** [comment]
Why are you using timescale?

**Comment by NealKaviratna** [comment]
Should I not be? I've never had to do pause functionality before.

**Comment by cookie966507** [comment]
It's bad practice. And usually it will cause the game to break because the update method is dependent on timescale being not 0. And also timescale doesn't stop everything (like animations, particles, etc). We usually have have game states and the in relevant scripts have if (in this state) run update

**Comment by JonathanHunter** [comment]
I already have pause handled for the most part all you have to do is change the game state variable to paused or something.

**Comment by NealKaviratna** [comment]
Gotcha, yeah I had timescale set to 0.00000001 to keep gui animations working. I'll change the implementation to use the game state variable when I push the new buttons.

**Pull request merged**
