### PR TITLE
Add Basic Particle Elements

### PR DESCRIPTION
**Pull request by NealKaviratna**

### CODE REVIEW

**Comment by JonathanHunter** [comment]
You have a bunch of weird standard assets, namely crossplatformInput, that probably shouldn't be there.  Also your trying to add meta files for folders that don't exist again.

**Comment by NealKaviratna** [comment]
Shuriken requires util, which requires cross platform input. 

I can delete the scripts associated with CrossPlatformInput if you'd like so we can remove it. The game will compile, but the shuriken particle stuff throws missing script warnings.

**Comment by NealKaviratna** [comment]
I already exported my standard assets used with dependencies selected. So everything in my commits is necessary.

Most of the Standard Assets files that make this PR up are the files from commit 9c1073e22a18541fc5cc927a3a699d34e6421126 where I handled merge conflicts between my branch and master ahead of time. So the fluff is from the Kartik stuff you pulled in I believe.

**Comment by NealKaviratna** [comment]
As far as the metadata goes, I'm not sure. I believe the Unity editor deletes any metadata that refers to nothing automatically.

Edit: Just looked at all the meta files in the commit. All of them reference something in the file structure. Are you sure the problem isn't on your end?

**Comment by JonathanHunter** [comment]
If they are required then its fine +1

**Pull request merged**
