### PR TITLE
New Models and Updating the Card.XML

### PR DESCRIPTION
**Pull request by zehro**
New Models
-Bo Staff
-Kanobo
-Tanto
-Tonfa
-Wakizashi

New Cards on XML
-Regular Fan/Wide Fan/Long Fan
-Tonfa
-Tanto
-Wakizashi
-Katana/Curved Blade/Wide Sword (previously Sword1/Sword2/Sword3)
-Ono
-Naginata
-Bo Staff
-Single/Double/Triple Bamboo Dart, Kunai, Shuriken, Sai

Updated Descriptions on XML

Redid Damage Balancing on XML

### CODE REVIEW

**Comment by NealKaviratna** [comment]
Only problem I could see is if other people are unaware of the name change for VerticalObjectSpawn. Even then it wouldn't be too much of an issue.

Looks good to me. :+1:

**Comment by JonathanHunter** [comment]
Why did you delete the spear card? And yes I saw you have a melee version of it in now.

**Comment by zehro** [comment]
Oh derp I thought we would use the naginata for melee instead of throwing.
I can re-add that if you'd like..

**Comment by JonathanHunter** [comment]
Yes, please re-add it.  Its the only projectile with piercing and we don't have the luxury of arbitrarily removing cards

**Comment by JonathanHunter** [comment]
Also be sure to use the original script

**Comment by zehro** [comment]
I was going to add other piecing cards. I have restored the SpearAction
class file in my fork, but is it okay to rename it to Piercing so other
piercing cards are not named after SpearAction on the Cards.xml?

**Comment by JonathanHunter** [comment]
The class name is not shown to the user ever, so you shouldn't need to change it.

**Comment by zehro** [comment]
Actually nevermind, the Fireball script actually does what I intended to
make for Piercing. I'll use Fireball for now

**Pull request closed without merging**
