### PR TITLE
Kartiks Environment

### PR DESCRIPTION
**Pull request by cookie966507**

### CODE REVIEW

**Comment by NealKaviratna** [comment]
So many files. Maybe we merge it into a working directory and see if we can scrape off some of the Standard Assets committed.

I know that can be a pain though. So +1 in the event the rest of the group is okay with all these files.

**Comment by JonathanHunter** [comment]
I'd rather not add 400 superfluous files.  I'm relatively free tomorrow , so I'll get the real pieces and merge them.

**Comment by NealKaviratna** [comment]
Sounds good. :100:

**Comment by JonathanHunter** [comment]
Some assets could be removed still, but they are all in one folder so I'll merge for now

**Pull request merged**
